{{--
    sidebar.blade.php — Bootstrap 4 Left Sidebar Example
    =====================================================
    Template: default (Bootstrap 4)
    Location: resources/views/default/template/admin/block/sidebar.blade.php

    Renders the left navigation sidebar including:
    - Logo / app name
    - Sidebar content widget (user profile, stats, etc.)
    - Navigation menu items

    Variables provided by the controller/middleware:
    - $logo              : string — path to logo image (relative to public/)
    - $appName           : string — application name
    - $sidebar_content   : string — HTML from canvastack_sidebar_content() via DefaultAdapter
    - $menu_sidebar      : array  — array of pre-rendered HTML strings for nav items
    - $components->meta->content['text']['app_name'] : string — app name from meta component

    Bootstrap 4 specific:
    - No framework-specific classes needed in this file
    - sidebar_content HTML uses pull-left (Bootstrap 4) via DefaultAdapter
    - Menu items may use Bootstrap 4 collapse for sub-menus
--}}
<?php
// Check if logo file exists locally
// If not, fall back to using $logo as a URL
$fileExists = file_exists(public_path() . $logo);
?>

<div class="sidebar-menu" role="navigation" aria-label="Main navigation">

    {{-- ── Sidebar header with logo ──────────────────────────────────── --}}
    <div class="sidebar-header">
        <div class="logo">
            @if ($fileExists)
                {{-- Logo image exists in public/ directory --}}
                <a href="{{ URL::to('admin') }}"
                   class="lights font-congenial-black color-transparent"
                   aria-label="{{ $appName }} — Go to dashboard">
                    <img src="{{ asset($logo) }}" alt="{{ $appName }}" />
                </a>
            @else
                {{-- Logo is a URL (external or CDN) --}}
                <a href="{{ URL::to('admin') }}"
                   class="lights font-congenial-black color-transparent"
                   aria-label="{{ $components->meta->content['text']['app_name'] }} — Go to dashboard">
                    <img src="{{ $logo }}"
                         alt="{{ $components->meta->content['text']['app_name'] }}" />
                    <span>{{ $components->meta->content['text']['app_name'] }}</span>
                </a>
            @endif
        </div>
    </div>

    {{--
        Sidebar content widget — rendered by canvastack_sidebar_content() via DefaultAdapter.
        DefaultAdapter::renderSidebarContent() produces Bootstrap 4 HTML with:
        - pull-left for avatar image alignment
        - media / media-body structure for user profile widget

        $sidebar_content is set by the controller.
        It may be empty if no sidebar widget is configured.
    --}}
    @if ($sidebar_content)
        {!! $sidebar_content !!}
    @endif

    {{--
        Navigation menu items.
        Each item in $menu_sidebar is a pre-rendered HTML string.
        Items are generated by the CanvaStack menu builder.

        Menu items may include:
        - Simple links: <a href="...">...</a>
        - Dropdown groups: <li class="dropdown">...</li>
        - Section headers: <li class="menu-header">...</li>

        MetisMenu.js (loaded via config) handles accordion behavior.
    --}}
    <nav class="menu-inner" aria-label="Sidebar navigation">
        @foreach ($menu_sidebar as $menu)
            {!! $menu !!}
        @endforeach
    </nav>

</div>{{-- .sidebar-menu --}}
